### ISSUE TITLE
Enhance settings and meta tab

### ISSUE THREAD

**Issue by ambros-gleixner** [ambros-gleixner/rubberband#32]
* [x] Like in the details tab, a search/filter box would be useful.
* [x] Can we create an option (toggle with a check box, or new tab?) such that only the parameters with different values are displayed?
* [x] A similar table design as the other tables would be good.

**Comment by fschloesser** [comment]
This has been completed in this commit: https://github.com/ambros-gleixner/rubberband/pull/26/commits/17c0525197b8bfcc2fc70d094d6406a9e649a117

**Comment by ambros-gleixner** [comment]
Two issues:
* In both tabs, in my firefox, the columns of the header row are not aligned with the columns of the table body. When I click to sort, then they align. The same in chromium.
* In chromium, the sort arrows do not appear.
Can you reproduce this?

And two questions:
* For Meta: What is again the difference between the two tables in the meta tab?  For a clueless user it is unclear. Either we should merge the tables or give a clarifying header for each.
* For Settings: Can you add an explanation text for the toggle (when moving the cursor over it like for the other buttons)?

**Comment by fschloesser** [comment]
I know about the first issue, it seems to be a datatables issue, the javascript plugin that formats the tables. I have no clue how to solve this. 

Concerning the second issue:
the second table is the information from the meta file.
I will try to add an explanation text.

**Comment by ambros-gleixner** [comment]
After adding some explanatory text above the bottom table this can be closed.
